### ISSUE TITLE
Export Parameters - Edit HRU Parameter table doesn't display all parameters generated

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#23] opened 2015-10-30 20:33 UTC
I haven't done a thorough check, but the hru_deplcrv parameters cannot be found in the editor.

**Comment by lbross** [comment] 2015-11-04 01:28
hru_deplcrv is a bagis-p parameter and should appear in red in the editor. It should be also viewable in the parameter viewer if the model runs successfully. Here is some more information on this parameter in the "tell me more" button from the timberline tool: 

"This tool allows users to specify a timberline elevation for each HRU zone in the AOI. The timberline values can be used to assign the Snowmelt Depletion Curve (hru_deplcrv) parameter values used in PRMS. This tool saves the timberline elevation values in the attribute table of the vector HRU featureclass (grid_zones_v). The timberline elevation will be recorded only in the attribute table of this featureclass and not be added to the exported OMS parameter files. A timberline elevation value of 0 indicates that the HRU is a regular HRU (not above timberline). The actual calculation of the hru_deplcrv is done by the hru_deplcrv_treeline parameter models built in ArcGIS ModelBuilder. Users can either use the timberline elevation extracted in this tool or the Landfire vegetation layer to set the values of hru_deplcrv. If the area of an HRU is more then 50% above timberline elevation or not covered by canopy vegetation, then the hru_deplcrv is set to 2, otherwise 1."

I confirmed that this parameter is listed in the bagis_parameters.txt file as a BAGIS parameter and it was visible in my hru parameters editor (in red)

**Comment by lbross** [comment] 2015-11-05 18:37
If a parameter is designated for BAGIS-P in the bagis_parameters.txt file and it is successfully calculated by a model, that parameter does not appear on the hru parameter editor. With our design, users aren't permitted to change the values calculated by the models. If the model fails, the parameter appears in red in the hru parameter editor and the user can overwrite the value.

If the parameter wasn't in  bagis_parameters.txt and not calculated by the model but was in the template, the user could also edit it in the hru parameter editor.

Closing issue because it is working as designed.

**Closed as completed by lbross** 2015-11-05 18:37 UTC
Labels: bug
